//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int OrderNum { get; set; }
        public string Counterparty { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> AuthorId { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
